### ISSUE TITLE
Invalid codec

### ISSUE THREAD

**Issue by henryiii** [henryiii/hypernewsviewer#13]
Error on https://test-hypernewsviewer.app.cern.ch/get/pi0calib/81

```
[2023-05-02 21:53:36,166] ERROR in app: Exception on /get/pi0calib/81 [GET]
Traceback (most recent call last):
File "/opt/app-root/lib64/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/opt/app-root/lib64/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/app-root/lib64/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/app-root/lib64/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/opt/app-root/lib64/python3.9/site-packages/hypernewsviewer/core.py", line 148, in get
body = forums.get_html(forum, path)
File "/opt/app-root/lib64/python3.9/site-packages/hypernewsviewer/model/structure.py", line 61, in get_html
return msg.read_text() if msg.exists() else None
File "/usr/lib64/python3.9/pathlib.py", line 1257, in read_text
return f.read()
File "/usr/lib64/python3.9/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 1856: invalid start byte
```

Also https://test-hypernewsviewer.app.cern.ch/get//HIN-19-011/79.

**Comment by henryiii** [comment]
Fixed.
